language: python
python:
  - 2.7

install: "pip install -r requirements.txt --use-mirrors"
script: nosetests

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-numpy python-scipy cython python-matplotlib python-pandas