language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - wget "http://repo.continuum.io/pkgs/free/linux-64/llvm-3.2-0.tar.bz2"
  - tar -xjf llvm-3.2-0.tar.bz2
  - PATH+=":`pwd`/bin"
  - export LD_LIBRARY_PATH="`pwd`/lib"
  - export LLVM_CONFIG_PATH="`pwd`/bin/llvm-config"
  - $LLVM_CONFIG_PATH --cflags
  - export LLVMPY_DYNLINK=1
  - pip -q install cython --install-option="--no-cython-compile"
  - pip -q install git+git://github.com/numpy/numpy.git
  - pip -q install git+git://github.com/scipy/scipy.git
  - pip -q install git+git://github.com/pydata/pandas.git
  - pip -q install six
  - pip -q install argparse
  - git clone git://github.com/llvmpy/llvmpy.git
  - cd llvmpy; python setup.py install -q; cd ..
  - pip -q install git+git://github.com/numba/numba.git
  - python setup.py -q install

script: make check

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libatlas-dev libsuitesparse-dev swig

virtualenv:
  system_site_packages: true
