language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - ci/install.sh

script: nosetests

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libatlas-base-dev

virtualenv:
  system_site_packages: true
