language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - pip install cython
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install

script: make check

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libatlas-dev libsuitesparse-dev swig

virtualenv:
  system_site_packages: true
