language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - pip install cython
  - pip install git+git://github.com/numpy/numpy.git
  - pip install git+git://github.com/scipy/scipy.git
  - pip install git+git://github.com/numba/numba.git
  - pip install git+git://github.com/pydata/pandas.git
  - pip install six
  - pip install argparse
  - python setup.py -q install

script: make check

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libatlas-dev libsuitesparse-dev swig

virtualenv:
  system_site_packages: true
