language: python
python:
  - 2.7

install: "pip install -r requirements.txt --use-mirrors"
script: nosetests --with-coverage --cover-package=span --cover-branches --cover-tests

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-scipy python-matplotlib cython python-tables

virtualenv:
  system_site_packages: true