language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - python setup.py -q install

script: make check

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gfortran libatlas-dev libsuitesparse-dev swig \
    python-numpy python-scipy python-pandas cython
  - pip install -q argparse six

virtualenv:
  system_site_packages: true
